// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_VITIS_LOOP_84_11_VITIS_LOOP_85_12_VITIS_LOOP_86_1310 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        output_conv3,
        grp_fu_2854_p_din0,
        grp_fu_2854_p_din1,
        grp_fu_2854_p_opcode,
        grp_fu_2854_p_dout0,
        grp_fu_2854_p_ce,
        grp_fu_11355_p_din0,
        grp_fu_11355_p_din1,
        grp_fu_11355_p_opcode,
        grp_fu_11355_p_dout0,
        grp_fu_11355_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [63:0] m_axi_gmem_WDATA;
output  [7:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [63:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] output_conv3;
output  [63:0] grp_fu_2854_p_din0;
output  [63:0] grp_fu_2854_p_din1;
output  [1:0] grp_fu_2854_p_opcode;
input  [63:0] grp_fu_2854_p_dout0;
output   grp_fu_2854_p_ce;
output  [63:0] grp_fu_11355_p_din0;
output  [63:0] grp_fu_11355_p_din1;
output  [4:0] grp_fu_11355_p_opcode;
input  [0:0] grp_fu_11355_p_dout0;
output   grp_fu_11355_p_ce;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg m_axi_gmem_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
reg    ap_block_state21_pp0_stage0_iter20;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln84_fu_250_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] bias_conv3_address0;
reg    bias_conv3_ce0;
wire   [63:0] bias_conv3_q0;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
reg    gmem_blk_n_AW;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln84_11_fu_306_p3;
reg   [3:0] select_ln84_11_reg_597;
reg   [3:0] select_ln84_11_reg_597_pp0_iter1_reg;
reg   [3:0] select_ln84_11_reg_597_pp0_iter2_reg;
reg   [3:0] select_ln84_11_reg_597_pp0_iter3_reg;
reg   [3:0] select_ln84_11_reg_597_pp0_iter4_reg;
reg   [3:0] select_ln84_11_reg_597_pp0_iter5_reg;
reg   [3:0] select_ln84_11_reg_597_pp0_iter6_reg;
reg   [60:0] trunc_ln89_2_reg_602;
reg   [63:0] gmem_addr_reg_607;
reg   [63:0] gmem_addr_reg_607_pp0_iter2_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter3_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter4_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter5_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter6_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter7_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter8_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter9_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter10_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter11_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter12_reg;
reg   [63:0] gmem_addr_reg_607_pp0_iter13_reg;
reg   [63:0] bias_conv3_load_reg_619;
reg   [63:0] gmem_addr_read_reg_624;
wire   [63:0] bitcast_ln89_fu_505_p1;
reg   [63:0] a_assign_2_reg_634;
reg   [63:0] a_assign_2_reg_634_pp0_iter13_reg;
wire   [63:0] select_ln89_fu_550_p3;
reg   [63:0] select_ln89_reg_640;
wire   [63:0] zext_ln84_6_fu_501_p1;
wire  signed [63:0] sext_ln89_2_fu_491_p1;
reg    ap_block_pp0_stage0_01001;
reg   [2:0] j_fu_104;
wire   [2:0] add_ln86_fu_446_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_load;
reg   [2:0] i_fu_108;
wire   [2:0] select_ln85_10_fu_400_p3;
reg   [2:0] ap_sig_allocacmp_i_6;
reg   [5:0] indvar_flatten1351_fu_112;
wire   [5:0] select_ln85_11_fu_458_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten1351_load;
reg   [3:0] num_ker_fu_116;
reg   [3:0] ap_sig_allocacmp_num_ker_3;
reg   [8:0] indvar_flatten1381_fu_120;
wire   [8:0] add_ln84_fu_256_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten1381_load;
wire   [3:0] empty_fu_212_p0;
wire   [6:0] empty_fu_212_p1;
wire   [5:0] p_shl_fu_222_p3;
wire   [6:0] p_shl50_cast_fu_230_p1;
wire   [6:0] zext_ln85_fu_218_p1;
wire   [6:0] empty_213_fu_234_p2;
wire  signed [9:0] p_cast112_fu_240_p1;
wire   [9:0] empty_fu_212_p2;
wire   [0:0] icmp_ln85_fu_274_p2;
wire   [3:0] add_ln84_2_fu_268_p2;
wire   [3:0] p_mid11363_fu_292_p0;
wire   [6:0] p_mid11363_fu_292_p1;
wire   [9:0] p_mid11363_fu_292_p2;
wire   [9:0] add_ln88_2_fu_244_p2;
wire   [0:0] icmp_ln86_fu_328_p2;
wire   [0:0] xor_ln84_fu_322_p2;
wire   [2:0] select_ln84_10_fu_280_p3;
wire   [0:0] and_ln84_fu_334_p2;
wire   [0:0] or_ln85_fu_346_p2;
wire   [2:0] add_ln85_2_fu_340_p2;
wire   [5:0] p_shl50_mid1_fu_364_p3;
wire   [6:0] p_shl50_cast_mid1_fu_372_p1;
wire   [6:0] zext_ln85_1_fu_360_p1;
wire   [6:0] p_mid11349_fu_376_p2;
wire  signed [9:0] p_cast112_mid1_fu_382_p1;
wire   [9:0] select_ln84_fu_298_p3;
wire   [9:0] add_ln88_fu_386_p2;
wire   [9:0] select_ln84_12_fu_314_p3;
wire   [2:0] select_ln85_8_fu_352_p3;
wire   [9:0] select_ln85_9_fu_392_p3;
wire   [9:0] zext_ln89_fu_408_p1;
wire   [9:0] add_ln89_fu_412_p2;
wire   [12:0] tmp_s_fu_418_p3;
wire  signed [63:0] sext_ln89_fu_426_p1;
wire   [63:0] add_ln89_2_fu_430_p2;
wire   [5:0] add_ln85_fu_452_p2;
wire   [63:0] bitcast_ln18_fu_509_p1;
wire   [10:0] tmp_13_fu_512_p4;
wire   [51:0] trunc_ln18_fu_522_p1;
wire   [0:0] icmp_ln18_5_fu_532_p2;
wire   [0:0] icmp_ln18_4_fu_526_p2;
wire   [0:0] or_ln18_fu_538_p2;
wire   [0:0] and_ln18_fu_544_p2;
reg    grp_fu_165_ce;
reg    grp_fu_169_ce;
reg    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [9:0] empty_fu_212_p00;
wire   [9:0] p_mid11363_fu_292_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_CNN_Pipeline_VITIS_LOOP_84_11_VITIS_LOOP_85_12_VITIS_LOOP_86_1310_bias_conv3_dEe #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
bias_conv3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_conv3_address0),
    .ce0(bias_conv3_ce0),
    .q0(bias_conv3_q0)
);

CNN_mul_4ns_7ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_4ns_7ns_10_1_1_U100(
    .din0(empty_fu_212_p0),
    .din1(empty_fu_212_p1),
    .dout(empty_fu_212_p2)
);

CNN_mul_4ns_7ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_4ns_7ns_10_1_1_U101(
    .din0(p_mid11363_fu_292_p0),
    .din1(p_mid11363_fu_292_p1),
    .dout(p_mid11363_fu_292_p2)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_250_p2 == 1'd0))) begin
            i_fu_108 <= select_ln85_10_fu_400_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_108 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_250_p2 == 1'd0))) begin
            indvar_flatten1351_fu_112 <= select_ln85_11_fu_458_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten1351_fu_112 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_250_p2 == 1'd0))) begin
            indvar_flatten1381_fu_120 <= add_ln84_fu_256_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten1381_fu_120 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_250_p2 == 1'd0))) begin
            j_fu_104 <= add_ln86_fu_446_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_104 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_250_p2 == 1'd0))) begin
            num_ker_fu_116 <= select_ln84_11_fu_306_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            num_ker_fu_116 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_assign_2_reg_634 <= grp_fu_2854_p_dout0;
        a_assign_2_reg_634_pp0_iter13_reg <= a_assign_2_reg_634;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        bias_conv3_load_reg_619 <= bias_conv3_q0;
        gmem_addr_read_reg_624 <= m_axi_gmem_RDATA;
        gmem_addr_reg_607_pp0_iter10_reg <= gmem_addr_reg_607_pp0_iter9_reg;
        gmem_addr_reg_607_pp0_iter11_reg <= gmem_addr_reg_607_pp0_iter10_reg;
        gmem_addr_reg_607_pp0_iter12_reg <= gmem_addr_reg_607_pp0_iter11_reg;
        gmem_addr_reg_607_pp0_iter13_reg <= gmem_addr_reg_607_pp0_iter12_reg;
        gmem_addr_reg_607_pp0_iter2_reg <= gmem_addr_reg_607;
        gmem_addr_reg_607_pp0_iter3_reg <= gmem_addr_reg_607_pp0_iter2_reg;
        gmem_addr_reg_607_pp0_iter4_reg <= gmem_addr_reg_607_pp0_iter3_reg;
        gmem_addr_reg_607_pp0_iter5_reg <= gmem_addr_reg_607_pp0_iter4_reg;
        gmem_addr_reg_607_pp0_iter6_reg <= gmem_addr_reg_607_pp0_iter5_reg;
        gmem_addr_reg_607_pp0_iter7_reg <= gmem_addr_reg_607_pp0_iter6_reg;
        gmem_addr_reg_607_pp0_iter8_reg <= gmem_addr_reg_607_pp0_iter7_reg;
        gmem_addr_reg_607_pp0_iter9_reg <= gmem_addr_reg_607_pp0_iter8_reg;
        select_ln84_11_reg_597_pp0_iter2_reg <= select_ln84_11_reg_597_pp0_iter1_reg;
        select_ln84_11_reg_597_pp0_iter3_reg <= select_ln84_11_reg_597_pp0_iter2_reg;
        select_ln84_11_reg_597_pp0_iter4_reg <= select_ln84_11_reg_597_pp0_iter3_reg;
        select_ln84_11_reg_597_pp0_iter5_reg <= select_ln84_11_reg_597_pp0_iter4_reg;
        select_ln84_11_reg_597_pp0_iter6_reg <= select_ln84_11_reg_597_pp0_iter5_reg;
        select_ln89_reg_640 <= select_ln89_fu_550_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        gmem_addr_reg_607 <= sext_ln89_2_fu_491_p1;
        select_ln84_11_reg_597_pp0_iter1_reg <= select_ln84_11_reg_597;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln84_fu_250_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln84_11_reg_597 <= select_ln84_11_fu_306_p3;
        trunc_ln89_2_reg_602 <= {{add_ln89_2_fu_430_p2[63:3]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln84_fu_250_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_6 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_6 = i_fu_108;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten1351_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1351_load = indvar_flatten1351_fu_112;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten1381_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1381_load = indvar_flatten1381_fu_120;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_104;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_num_ker_3 = 4'd0;
    end else begin
        ap_sig_allocacmp_num_ker_3 = num_ker_fu_116;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bias_conv3_ce0 = 1'b1;
    end else begin
        bias_conv3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_165_ce = 1'b1;
    end else begin
        grp_fu_165_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_169_ce = 1'b1;
    end else begin
        grp_fu_169_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_2_fu_268_p2 = (ap_sig_allocacmp_num_ker_3 + 4'd1);

assign add_ln84_fu_256_p2 = (ap_sig_allocacmp_indvar_flatten1381_load + 9'd1);

assign add_ln85_2_fu_340_p2 = (select_ln84_10_fu_280_p3 + 3'd1);

assign add_ln85_fu_452_p2 = (ap_sig_allocacmp_indvar_flatten1351_load + 6'd1);

assign add_ln86_fu_446_p2 = (select_ln85_8_fu_352_p3 + 3'd1);

assign add_ln88_2_fu_244_p2 = ($signed(p_cast112_fu_240_p1) + $signed(empty_fu_212_p2));

assign add_ln88_fu_386_p2 = ($signed(p_cast112_mid1_fu_382_p1) + $signed(select_ln84_fu_298_p3));

assign add_ln89_2_fu_430_p2 = ($signed(sext_ln89_fu_426_p1) + $signed(output_conv3));

assign add_ln89_fu_412_p2 = (select_ln85_9_fu_392_p3 + zext_ln89_fu_408_p1);

assign and_ln18_fu_544_p2 = (or_ln18_fu_538_p2 & grp_fu_11355_p_dout0);

assign and_ln84_fu_334_p2 = (xor_ln84_fu_322_p2 & icmp_ln86_fu_328_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (m_axi_gmem_WREADY == 1'b0)) | ((m_axi_gmem_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (m_axi_gmem_WREADY == 1'b0)) | ((m_axi_gmem_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_pp0_stage0_iter20 = (m_axi_gmem_BVALID == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bias_conv3_address0 = zext_ln84_6_fu_501_p1;

assign bitcast_ln18_fu_509_p1 = a_assign_2_reg_634_pp0_iter13_reg;

assign bitcast_ln89_fu_505_p1 = gmem_addr_read_reg_624;

assign empty_213_fu_234_p2 = (p_shl50_cast_fu_230_p1 - zext_ln85_fu_218_p1);

assign empty_fu_212_p0 = empty_fu_212_p00;

assign empty_fu_212_p00 = ap_sig_allocacmp_num_ker_3;

assign empty_fu_212_p1 = 10'd49;

assign grp_fu_11355_p_ce = grp_fu_169_ce;

assign grp_fu_11355_p_din0 = a_assign_2_reg_634;

assign grp_fu_11355_p_din1 = 64'd0;

assign grp_fu_11355_p_opcode = 5'd2;

assign grp_fu_2854_p_ce = grp_fu_165_ce;

assign grp_fu_2854_p_din0 = bias_conv3_load_reg_619;

assign grp_fu_2854_p_din1 = bitcast_ln89_fu_505_p1;

assign grp_fu_2854_p_opcode = 2'd0;

assign icmp_ln18_4_fu_526_p2 = ((tmp_13_fu_512_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln18_5_fu_532_p2 = ((trunc_ln18_fu_522_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_250_p2 = ((ap_sig_allocacmp_indvar_flatten1381_load == 9'd392) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_274_p2 = ((ap_sig_allocacmp_indvar_flatten1351_load == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_328_p2 = ((ap_sig_allocacmp_j_load == 3'd7) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = sext_ln89_2_fu_491_p1;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = gmem_addr_reg_607_pp0_iter13_reg;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_WDATA = select_ln89_reg_640;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 8'd255;

assign m_axi_gmem_WUSER = 1'd0;

assign or_ln18_fu_538_p2 = (icmp_ln18_5_fu_532_p2 | icmp_ln18_4_fu_526_p2);

assign or_ln85_fu_346_p2 = (icmp_ln85_fu_274_p2 | and_ln84_fu_334_p2);

assign p_cast112_fu_240_p1 = $signed(empty_213_fu_234_p2);

assign p_cast112_mid1_fu_382_p1 = $signed(p_mid11349_fu_376_p2);

assign p_mid11349_fu_376_p2 = (p_shl50_cast_mid1_fu_372_p1 - zext_ln85_1_fu_360_p1);

assign p_mid11363_fu_292_p0 = p_mid11363_fu_292_p00;

assign p_mid11363_fu_292_p00 = add_ln84_2_fu_268_p2;

assign p_mid11363_fu_292_p1 = 10'd49;

assign p_shl50_cast_fu_230_p1 = p_shl_fu_222_p3;

assign p_shl50_cast_mid1_fu_372_p1 = p_shl50_mid1_fu_364_p3;

assign p_shl50_mid1_fu_364_p3 = {{add_ln85_2_fu_340_p2}, {3'd0}};

assign p_shl_fu_222_p3 = {{ap_sig_allocacmp_i_6}, {3'd0}};

assign select_ln84_10_fu_280_p3 = ((icmp_ln85_fu_274_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_i_6);

assign select_ln84_11_fu_306_p3 = ((icmp_ln85_fu_274_p2[0:0] == 1'b1) ? add_ln84_2_fu_268_p2 : ap_sig_allocacmp_num_ker_3);

assign select_ln84_12_fu_314_p3 = ((icmp_ln85_fu_274_p2[0:0] == 1'b1) ? p_mid11363_fu_292_p2 : add_ln88_2_fu_244_p2);

assign select_ln84_fu_298_p3 = ((icmp_ln85_fu_274_p2[0:0] == 1'b1) ? p_mid11363_fu_292_p2 : empty_fu_212_p2);

assign select_ln85_10_fu_400_p3 = ((and_ln84_fu_334_p2[0:0] == 1'b1) ? add_ln85_2_fu_340_p2 : select_ln84_10_fu_280_p3);

assign select_ln85_11_fu_458_p3 = ((icmp_ln85_fu_274_p2[0:0] == 1'b1) ? 6'd1 : add_ln85_fu_452_p2);

assign select_ln85_8_fu_352_p3 = ((or_ln85_fu_346_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_load);

assign select_ln85_9_fu_392_p3 = ((and_ln84_fu_334_p2[0:0] == 1'b1) ? add_ln88_fu_386_p2 : select_ln84_12_fu_314_p3);

assign select_ln89_fu_550_p3 = ((and_ln18_fu_544_p2[0:0] == 1'b1) ? bitcast_ln18_fu_509_p1 : 64'd0);

assign sext_ln89_2_fu_491_p1 = $signed(trunc_ln89_2_reg_602);

assign sext_ln89_fu_426_p1 = $signed(tmp_s_fu_418_p3);

assign tmp_13_fu_512_p4 = {{bitcast_ln18_fu_509_p1[62:52]}};

assign tmp_s_fu_418_p3 = {{add_ln89_fu_412_p2}, {3'd0}};

assign trunc_ln18_fu_522_p1 = bitcast_ln18_fu_509_p1[51:0];

assign xor_ln84_fu_322_p2 = (icmp_ln85_fu_274_p2 ^ 1'd1);

assign zext_ln84_6_fu_501_p1 = select_ln84_11_reg_597_pp0_iter6_reg;

assign zext_ln85_1_fu_360_p1 = add_ln85_2_fu_340_p2;

assign zext_ln85_fu_218_p1 = ap_sig_allocacmp_i_6;

assign zext_ln89_fu_408_p1 = select_ln85_8_fu_352_p3;

endmodule //CNN_CNN_Pipeline_VITIS_LOOP_84_11_VITIS_LOOP_85_12_VITIS_LOOP_86_1310
